version: '3'

services:

  postgres:
    image: 'postgres:14'
    container_name: 'security-postgres'
    restart: always
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=123'
      - 'POSTGRES_DB=security_db'
    networks:
      - security-network

  app:
    build: ./
    container_name: 'auth-app'
    ports:
        - "8085:8085"
    depends_on:
      - postgres
    environment:
      - 'DB_SERVER=postgres'
    links:
      - postgres
    networks:
      - security-network

 
networks:
  security-network:
    driver: bridge


